repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-illegal-windows-names
      - id: detect-private-key
      - id: forbid-submodules

  - repo: 'https://github.com/FeryET/pre-commit-rust'
    rev: v1.2.1
    hooks:
      - id: cargo-check
      - id: clippy
      - id: fmt

  - repo: 'https://github.com/rhysd/actionlint'
    rev: v1.7.11
    hooks:
      - id: actionlint

ci:
  skip:
    - fmt
    - cargo-check
    - clippy
