[package]
name = "es_runway_selector"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cargo-license = "0.7.0"
clap = { version = "4.5.49", features = ["derive"] }
config = { version = "0.15.18", features = ["indexmap", "preserve_order"] }
csv = "1.4.0"
directories = "6.0.0"
encoding = "0.2.33"
futures = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
jiff = { workspace = true }
metar_decoder = { path = "../metar_decoder" }
nom = { workspace = true }
regex = "1.12.2"
reqwest = { workspace = true }
self_update = { version = "0.42.0", features = ["compression-zip-deflate", "rustls", "archive-tar"], default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tabled = "0.20.0"
thiserror = "2.0.17"
tokio = { workspace = true }
toml = { version = "0.9.8", features = ["preserve_order"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-unwrap = { workspace = true }
walkdir = "2.5.0"
whoami = "1.6.1"

[target.'cfg(not(target_env = "musl"))'.dependencies]
rfd = "0.15.4"

[target.'cfg(target_env = "musl")'.dependencies]
ratatui = "0.29.0"
ratatui-explorer = "0.2.1"
crossterm = "0.29.0"

[dev-dependencies]
tracing-test = { workspace = true }
