es_main_window_delay_ms = 2000

ignore_airports = [
  "ENAE",
  "ENAS",
  "ENAX",
  "ENBB",
  "ENBM",
  "ENDI",
  "ENDO",
  "ENEG",
  "ENEN",
  "ENFG",
  "ENFY",
  "ENGK",
  "ENGN",
  "ENGS",
  "ENHA",
  "ENHS",
  "ENHT",
  "ENJA",
  "ENJB",
  "ENKJ",
  "ENKL",
  "ENLB",
  "ENLI",
  "ENLU",
  "ENLV",
  "ENMO",
  "ENOP",
  "ENRE",
  "ENRG",
  "ENRI",
  "ENRK",
  "ENSI",
  "ENSN",
  "ENSU",
  "ENTS",
  "ENTY",
  "ENUL",
  "ENVE",
  "ENQC",  # bad autometars
  "ENOA",  # writes qnh without Q in metar
]

[default_runways]
ENAL = 24
ENAN = 14
ENAT = 11
ENBL = 25
ENBN =  3
ENBO =  7
ENBR = 17
ENBS = 21
ENBV = 24
ENCN = 21
ENDU = 28
ENEV = 17
ENFL =  7
ENGM =  1
ENHK = 29
ENHD = 13
ENKB =  7
ENKR = 23
ENLK =  2
ENML =  7
ENMS = 33
ENNA = 34
ENNO = 12
ENOL = 15
ENRA = 31
ENRO = 31
ENRY = 30
ENSD = 26
ENSG = 24
ENSH = 36
ENSO = 14
ENST =  2
ENTC = 18
ENTO = 18
ENVA =  9
ENZV = 18
